package chaojidou

const (
	SOGOU_PROCESS_NAME = "SogouExplorer.exe"
	QQ_PROCESS_NAME    = "QQBrowser.exe"
	T360_PROCESS_NAME = ""
	CHROME_PROCESS_NAME = ""
	OFFICIALCLIENT_PROCESS_NAME = ""

	WAITING_ACTIVE_PID_MILLI_SECONDS = 1000
)
